"""
create_pptx tool - server-side PowerPoint generation (client-side, on-device).

Why this exists: on LLM_PROVIDER=openai_compatible there is no code_execution
container and no Files API - both are Anthropic server features (see
core/llm_providers/openai_compatible.py). The model therefore cannot generate
a .pptx by writing python-pptx code in a sandbox. This tool gives it the same
capability declaratively: the model describes the slides (title + bullets per
slide, optional two-column layout), this module builds the file in-process with
python-pptx, and the result is saved to the local attachment store where the
send_message tool (attach_outputs) can pick it up and ship it to Discord.

The model passes back the exact `save_path` reported in the tool result to
attach the file - like a container output filename, but sourced from the local
store instead. Files persist across turns.
"""
import asyncio
import logging
import re
from typing import Any, Dict, List, Optional

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    _PPTX_AVAILABLE = True
except ImportError:
    _PPTX_AVAILABLE = False
    Presentation = None

from core.local_attachment_store import LocalAttachmentStore

logger = logging.getLogger(__name__)

CREATE_PPTX_TOOL = {
    "name": "create_pptx",
    "description": (
        "Create a PowerPoint (.pptx) presentation and save it where it can be "
        "sent to Discord. Provide the presentation title and an ordered list of "
        "slides; each slide has a title and bullet points (plain text, no "
        "markdown). Use this instead of code execution on this provider. The "
        "tool result reports the saved file path - pass it to send_message's "
        "attach_outputs to deliver the file, e.g. attach_outputs=[\"report.pptx\"]."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "description": "Presentation title (used for the deck filename and cover slide).",
            },
            "slides": {
                "type": "array",
                "description": "Slides in order, each a title plus bullet points.",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string", "description": "Slide title"},
                        "bullets": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "Bullet points for this slide (plain text).",
                        },
                        "subtitle": {
                            "type": "string",
                            "description": "Optional subtitle line under the title.",
                        },
                    },
                    "required": ["title"],
                },
            },
        },
        "required": ["title", "slides"],
    },
}


def get_create_pptx_tool() -> dict:
    return CREATE_PPTX_TOOL


def _sanitize(name: str) -> str:
    """Filename-safe slug for a model-supplied title (keep letters/digits/-_)."""
    slug = re.sub(r"[^A-Za-z0-9_-]+", "-", name or "").strip("-_")
    return (slug or "presentation")[:60]


def _slugified_filename(title: str) -> str:
    return f"{_sanitize(title)}.pptx"


def _build_pptx(title: str, slides: List[dict]) -> bytes:
    """Synchronous python-pptx build; returns the .pptx bytes."""
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Title (cover) slide - first slide layout is usually the title layout
    try:
        cover = prs.slides.add_slide(prs.slide_layouts[0])
    except Exception:
        cover = prs.slides.add_slide(prs.slide_layouts[1])
    if cover.shapes.title is not None:
        cover.shapes.title.text = title
    if cover.placeholders and len(cover.placeholders) > 1:
        body = cover.placeholders[1]
        try:
            body.text = "Generated by your Discord agent"
        except Exception:
            pass

    for slide_spec in slides:
        slide_title = (slide_spec.get("title") or "").strip() or "Slide"
        bullets = [str(b).strip() for b in (slide_spec.get("bullets") or []) if str(b).strip()]
        subtitle = (slide_spec.get("subtitle") or "").strip()

        try:
            layout = prs.slide_layouts[1]  # Title and Content
            slide = prs.slides.add_slide(layout)
        except Exception:
            slide = prs.slides.add_slide(prs.slide_layouts[5])

        if slide.shapes.title is not None:
            slide.shapes.title.text = slide_title

        body_placeholder = None
        for ph in slide.placeholders:
            if ph.placeholder_format.idx == 1:
                body_placeholder = ph
                break
        if body_placeholder is None and slide.placeholders:
            body_placeholder = slide.placeholders[0] if slide.placeholders[0] != slide.shapes.title else None

        if body_placeholder is not None:
            if subtitle:
                body_placeholder.text = subtitle + "\n" + "\n".join(f"• {b}" for b in bullets)
            else:
                body_placeholder.text = "\n".join(f"• {b}" for b in bullets) if bullets else ""

    import io
    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


class PptxBuilder:
    """Stateful executor for the create_pptx tool - holds a LocalAttachmentStore."""

    def __init__(self, local_store: LocalAttachmentStore):
        self.local_store = local_store

    async def execute(self, tool_input: dict) -> str:
        try:
            title = (tool_input.get("title") or "").strip()
            slides = tool_input.get("slides") or []
            if not title:
                return "Error: 'title' is required"
            if not isinstance(slides, list) or not slides:
                return "Error: 'slides' must be a non-empty list"
            if not _PPTX_AVAILABLE:
                return (
                    "Error: python-pptx is not installed in this environment "
                    "(add python-pptx to requirements to enable create_pptx)"
                )

            data = await asyncio.to_thread(_build_pptx, title, slides)
            filename = _slugified_filename(title)
            save_path = await self.local_store.save(filename, data)

            size_kb = round(len(data) / 1024, 1)
            count = len(slides)
            return (
                f"Created presentation '{title}' ({count} slide{'s' if count != 1 else ''}, "
                f"{size_kb} KB). Saved locally as '{filename}' at {save_path}. "
                f"Send it to Discord with send_message attach_outputs=[\"{filename}\"]."
            )
        except Exception as e:
            logger.error(f"create_pptx failed: {e}", exc_info=True)
            return f"Error creating presentation: {e}"